# Generated by Django 4.0.4 on 2022-05-05 13:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_id", models.CharField(max_length=60, unique=True)),
                ("label", models.CharField(max_length=60)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
