# Generated by Django 4.0.4 on 2022-05-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotationsdatabase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageannotation",
            name="height",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="imageannotation",
            name="image_correctness",
            field=models.CharField(
                choices=[
                    ("KO", "Ko"),
                    ("TO_BE_CHECKED", "To Be Checked"),
                    ("OK", "Ok"),
                ],
                default="TO_BE_CHECKED",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="imageannotation",
            name="label_correctness",
            field=models.CharField(
                choices=[
                    ("KO", "Ko"),
                    ("TO_BE_CHECKED", "To Be Checked"),
                    ("OK", "Ok"),
                ],
                default="TO_BE_CHECKED",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="imageannotation",
            name="width",
            field=models.IntegerField(default=-1),
        ),
    ]
